/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   vaadin-time-picker.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

export * from './src/vaadin-time-picker.js';
export * from './@types/interfaces';
